"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class lcmt_so101_grasp(object):

    __slots__ = ["grasp"]

    __typenames__ = ["double"]

    __dimensions__ = [[12]]

    def __init__(self):
        self.grasp = [ 0.0 for dim0 in range(12) ]
        """ LCM Type: double[12] """

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_so101_grasp._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>12d', *self.grasp[:12]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_so101_grasp._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_so101_grasp._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = lcmt_so101_grasp()
        self.grasp = struct.unpack('>12d', buf.read(96))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if lcmt_so101_grasp in parents: return 0
        tmphash = (0x472f6bb0665a25ba) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if lcmt_so101_grasp._packed_fingerprint is None:
            lcmt_so101_grasp._packed_fingerprint = struct.pack(">Q", lcmt_so101_grasp._get_hash_recursive([]))
        return lcmt_so101_grasp._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcmt_so101_grasp._get_packed_fingerprint())[0]

